### ISSUE TITLE
Cannot find module qw-page

### ISSUE THREAD

**Issue by jrpool** [qualweb/qualweb#229]
Starting on 16 December 2024, `qualweb.evaluate()` is always failing with the error message “Cannot find module `qw-page`”. Installing `qw-page` then results in an error message ”Cannot find module `util`”. Installing `util` then results in an error message

```
puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72
            this._reject(callback, new Errors_js_1.TargetCloseError('Target closed'));
```

The original error has this require stack:

```
Error: Cannot find module '@qualweb/qw-page'
Require stack:
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/index.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/qualweb.js
- /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/index.js
- /Users/c162712/Documents/repos/poolcvs/testaro/tests/qualWeb.js
- /Users/c162712/Documents/repos/poolcvs/testaro/procs/doTestAct.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at QualwebPage.addNecessaryScripts (/Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js:76:27)
    at QualwebPage.getTestingData (/Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/QualwebPage.object.js:71:14)
    at async EvaluationManager.evaluate (/Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/lib/EvaluationManager.object.js:12:29)
    at async /Users/c162712/Documents/repos/poolcvs/testaro/node_modules/@qualweb/core/dist/qualweb.js:65:44 {
  code: 'MODULE_NOT_FOUND',
```

`evaluate` is being called on line 136 at `https://github.com/cvs-health/testaro/blob/qwfix/tests/qualWeb.js`.

This error behavior began immediately after I updated dependencies, including updating `qualweb/core` from 0.7.80 to 0.8.1. This update is at `https://github.com/cvs-health/testaro/commit/740858c747a43c2d66f9d07f78dc8decbec79bf6`.

When I revert the `@qualweb/core` dependency to 0.7.80, the error disappears.

**Comment by Tellus** [comment]
We've released the fix on the main branch and it should be available in NPM now. I'll close this issue as fixed but do re-open if the problem persists.
